### ISSUE TITLE
Failed with {cant_open_file,"test",eisdir}

### ISSUE THREAD

**Issue by excavador** [nifoc/ecoveralls#1]
Hello,

I attempt to use your library for my erlang project, and meet problems:
https://travis-ci.org/zamotivator/qlp/builds/43969007

I can not understand, how to fix this problem.
Can you help me, please?

```
0.66s$ make coverage-report
 GEN    coverage-report
{"init terminating in do_boot",{{badmatch,{error,{cant_open_file,"test",eisdir}}},[{ecoveralls,analyse,2,[{file,"src/ecoveralls.erl"},{line,86}]},{ecoveralls,report,2,[{file,"src/ecoveralls.erl"},{line,94}]},{ecoveralls,travis_ci,2,[{file,"src/ecoveralls.erl"},{line,57}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by nifoc** [comment]
Hi,

I think that - for whatever reason - the `CoverData` variable is set to an incorrect value/path. In order to confirm that, I added some debug logging to the development branch.

`make coverage-report` should now include a line that looks something like this:

```
Analysing file: /Users/daniel/Documents/OSS/ecoveralls/test/cover_SUITE_data/test.coverdata
```

Can you please depend on the `development` branch and run your tests again?

Thank you!

**Comment by excavador** [comment]
https://travis-ci.org/zamotivator/qlp/builds/44440342

```
$ make coverage-report
GEN    coverage-report
Analysing file: test
{"init terminating in do_boot",{{badmatch,{error,{cant_open_file,"test",eisdir}}},[{ecoveralls,analyse,2,[{file,"src/ecoveralls.erl"},{line,87}]},{ecoveralls,report,2,[{file,"src/ecoveralls.erl"},{line,95}]},{ecoveralls,travis_ci,2,[{file,"src/ecoveralls.erl"},{line,57}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by nifoc** [comment]
Hi,

I think I know why it can't find a `*.coverdata` file.

In your `Makefile`, you have to explicitly tell Common Test about the `cover.spec` file. In your specific case, the `CT_OPTS` variable has to be set to:

``` makefile
CT_OPTS += -boot start_sasl -erl_args -config config/test.config -cover ./test/cover.spec
```

I updated the REAMDE to reflect this as well. Sorry about not noticing/mentioning this before.

I hope it works now!

**Comment by excavador** [comment]
Hi,
Thank you very much. Unfortunatelly, still does not work: https://travis-ci.org/zamotivator/qlp/builds/44969084#L1016

**Comment by nifoc** [comment]
``` makefile
CT_OPTS += -boot start_sasl -cover ./test/cover.spec -erl_args -config config/test.config
```

(Notice that the order has changed)

Did not notice the `-erl_args` in there at first :)

**Comment by excavador** [comment]
Thanks, now it works!
https://travis-ci.org/zamotivator/qlp/builds/45457221

:)
